### ISSUE TITLE
Multi-mod workspaces with dependencies have duplicate Minecraft entries in the classpath

### ISSUE THREAD

**Issue by FiniteReality** [neoforged/FancyModLoader#124]
This causes https://github.com/neoforged/FancyModLoader/blob/main/loader/src/main/java/net/neoforged/fml/util/DevEnvUtils.java#L72 to throw when it detects multiple Minecraft classes on the classpath

**Comment by FiniteReality** [comment]
A workaround is to declare Neo dependencies against the `compileOnly` configuration in the build.gradle for either the main, or the dependent mods

**Comment by Matyrobbrt** [comment]
I would not call this a bug, more like an intended feature. Your "workaround" is how you should declare your dependencies to begin with, the dependency on NeoForge should not be leaked, as that will cause issues for the consumers of your artifact too.

**Comment by FiniteReality** [comment]
> the dependency on NeoForge should not be leaked, as that will cause issues for the consumers of your artifact too.
But you need NeoForge in compileClasspath AND runtimeClasspath, but not leaked to consumers - there's no way to do this by default in gradle so you *need* a custom configuration. This is a huge pain compared to previous versions.

**Comment by FiniteReality** [comment]
> Well, I still do not quite understand why Gradle is not collapsing this dependency 🤔

Each project has its own generated neoforge repo, and since the artifacts are different it passes them all, is my undersatnding

**Comment by Shadows-of-Fire** [comment]
Is this issue also the cause of https://github.com/neoforged/NeoGradle/issues/162?

**Comment by marchermans** [comment]
> > Well, I still do not quite understand why Gradle is not collapsing this dependency 🤔
> 
> Each project has its own generated neoforge repo, and since the artifacts are different it passes them all, is my undersatnding

Gradle will do that, but the IDE won't it looks like.
Gradle resolves based on the GAV and will only pass one into the classpath of the run.
The IDE has no such idea, it just passes them in all together.

NG7 should collapse them yeah (it currently does not because it creates one IVY repo per project, but that is fixable by using the root project instead, plus some fenagling with task dependencies). But this problem always existed (different ATs, different subprojects with minecraft etc) and FML handled that always gracefully.

What changed that it does not do that now?

**Comment by FiniteReality** [comment]
This was resolved with a change to NeoGradle: https://github.com/neoforged/NeoGradle/pull/167 - as far as I understand the error for duplicate minecraft jars is now intended behaviour, and it's on tools like Gradle to properly remove the duplicates.
